### ISSUE TITLE
Push error

### ISSUE THREAD

**Issue by Tox1cCoder** [qvan7um/CS112#3]
Bạn ơi hình như bạn lock permission rồi mình push nó báo access denied

**Comment by qvan7um** [comment]
Bạn cho mình thêm chi tiết lỗi của bạn được không?

**Comment by Tox1cCoder** [comment]
![image](https://user-images.githubusercontent.com/92375607/226558907-340db685-cc1e-4505-98ef-e1bc170410ec.png)
Mình làm theo hướng dẫn xong nó báo như này, với bạn mình push cũng bị giống vậy ấy

**Comment by Tox1cCoder** [comment]
Mình push đc r
